analyzer:
  errors:
    library_private_types_in_public_api: ignore
    overridden_fields: ignore
    lines_longer_than_80_chars: false
    unintended_html_in_doc_comment: ignore
    one_member_abstracts: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

include: package:very_good_analysis/analysis_options.7.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false

line_length: 120