name: rankings
description: A Flutter app for querying rankings
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  envied: ^1.0.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hooks_riverpod: ^2.6.1
  hugeicons: ^0.0.7
  intl: ^0.19.0
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.3.1
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
